import { COLORS } from './theme';

export const I18N = {
    en: {
        explorer: "Explorer", settings: "Settings", newNode: "New Node", sceneOutline: "SCENE OUTLINE",
        theme: "Theme", gravity: "Gravity", centering: "Centering", distance: "Distance", showTooltips: "Show Tooltips",
        showMinimap: "Show Minimap", PHYandLAY: "Physics & Layout",searchText: "Search...", livePreview: "Live Preview",
        language: "Language", export: "Export", import: "Import", editNode: "Edit Node Content",
        id: "Unique ID", idHelp: "Only letters, numbers, and underscores.",
        title: "Title", type: "Type", color: "Color", template: "LaTeX Template",
        segments: "Interactive Segments", addSegment: "Add Segment", note: "Note (Markdown)",
        cancel: "Cancel", save: "Save Changes", delete: "Delete Node", tooltipSettings: "Tooltip Settings",
        customizeConnection: "Customize Connection", edgeLabel: "Edge Label", lineStyle: "Line Style",
        stroke: "Stroke", endpoint: "Endpoint", showArrowInMiddle: "Show Arrow in Middle",
        showEdgeLabels: "Show Edge Labels", edgeLabelMode: "Label Position", edgeLabelBg: "Label Background",
        minimapLabel: "Minimap Label", id: "ID", title: "Title", none: "None",
        pixelMode: "Pixel Mode", pixelFont: "Use Pixel Font", pixelMath: "Use Pixel Math", minimalMode: "Minimal Mode",
        expandAll: "Expand All", autoArrange: "Auto Arrange",
        focus: "Focus", pin: "Pin", unpin: "Unpin", hide: "Hide", show: "Show", edit: "Edit",
        library: "Library", searchLibrary: "Search library...", importLibrary: "Import Library", exportLibrary: "Export Library",
        folder: "Folder", tags: "Tags", moveToRoot: "Move to Root", editTemplate: "Edit Template", rename: "Rename", duplicate: "Duplicate",
        newFolder: "New Folder", treeView: "Tree View", listView: "List View", gridView: "Grid View", viewSwitcher: "View Switcher",
        collapseAll: "Collapse All", refresh: "Refresh",
        align: "Align", alignLeft: "Left", alignRight: "Right", alignTop: "Top", alignBottom: "Bottom", alignCenterH: "Center H", alignCenterV: "Center V",
        shortcuts: { new: "New Node", refresh: "Refresh View", copy: "Copy", paste: "Paste", cut: "Cut", delete: "Delete", toggleViewMode: "Toggle View Mode" },
        types: { default: "Default", axiom: "Axiom", constant: "Constant", parameter: "Parameter", note: "Note" },
        noSegments: "No segments defined.", connectionStyle: "Connection Style", targetId: "Target ID", linkColor: "Link Color",
        tooltipPlaceholder: "Tooltip content...", titlePlaceholder: "Title...", contentPlaceholder: "Content...",
        general: "General", appearance: "Appearance", physics: "Physics", layout: "Layout", shortcutsTab: "Shortcuts",
        collisionPadding: "Collision Padding", minimalGapRatio: "Minimal Gap", segmentHighlights: "Show Highlights",
        center: "Center", side: "Side", box: "Box",
        repel: "Repel", attract: "Attract", linkGap: "Link Gap",
        noNodes: "No nodes found",
        text: "Text", link: "Link",
        viewModeReadOnly: "View Mode (Read Only)", editMode: "Edit Mode",
        deleteConfirmation: "Are you sure you want to delete",
        confirm: "Confirm", ok: "OK", error: "Error", invalidFile: "Invalid MathMap file",
        importFailed: "Import failed", sceneLoaded: "Scene loaded", libraryLoaded: "Library loaded",
        file: "File", undo: "Undo", redo: "Redo", autoSave: "Auto Save",
        newScene: "New Scene", openScene: "Open Scene", saveScene: "Save Scene", saveAsScene: "Save As Scene",
        modified: "Modified", unsavedChanges: "Unsaved changes", close: "Close", saving: "Saving..."
    },
    zh: {
        explorer: "导航", settings: "设置", newNode: "新建节点", sceneOutline: "场景大纲",
        theme: "主题", gravity: "斥力强度", centering: "引力强度", distance: "连线距离", showTooltips: "显示提示框",
        showMinimap: "显示小地图", PHYandLAY: "物理与布局",searchText: "搜索...",livePreview: "实时预览",
        language: "语言", export: "导出", import: "导入", editNode: "编辑节点内容",
        id: "ID", idHelp: "仅限字母、数字和下划线。",
        title: "标题", type: "类型", color: "颜色", template: "LaTeX 模板",
        segments: "交互片段", addSegment: "添加片段", note: "备注 (Markdown)",
        cancel: "取消", save: "保存更改", delete: "删除节点", tooltipSettings: "提示框设置",
        customizeConnection: "自定义连线", edgeLabel: "连线标签", lineStyle: "连线样式",
        stroke: "线条", endpoint: "终点", showArrowInMiddle: "显示中间箭头",
        showEdgeLabels: "显示连线标签", edgeLabelMode: "标签位置", edgeLabelBg: "标签背景",
        minimapLabel: "小地图标签", id: "ID", title: "标题", none: "无",
        pixelMode: "像素模式", pixelFont: "使用像素字体", pixelMath: "使用像素数学", minimalMode: "极简模式",
        expandAll: "展开全部", autoArrange: "自动排列",
        focus: "聚焦", pin: "固定", unpin: "取消固定", hide: "隐藏", show: "显示", edit: "编辑",
        library: "库", searchLibrary: "搜索库...", importLibrary: "导入库", exportLibrary: "导出库",
        folder: "文件夹", tags: "标签", moveToRoot: "移动到根目录", editTemplate: "编辑模板", rename: "重命名", duplicate: "复制",
        newFolder: "新建文件夹", treeView: "树状视图", listView: "列表视图", gridView: "网格视图", viewSwitcher: "视图切换",
        collapseAll: "折叠全部", refresh: "刷新",
        align: "对齐", alignLeft: "左对齐", alignRight: "右对齐", alignTop: "顶对齐", alignBottom: "底对齐", alignCenterH: "水平居中", alignCenterV: "垂直居中",
        shortcuts: { new: "新建节点", refresh: "刷新视图", copy: "复制", paste: "粘贴", cut: "剪切", delete: "删除", toggleViewMode: "切换视图模式" },
        types: { default: "默认", axiom: "公理", constant: "常数", parameter: "参数", note: "注释" },
        noSegments: "未定义片段。", connectionStyle: "连接样式", targetId: "目标 ID", linkColor: "连线颜色",
        tooltipPlaceholder: "提示框内容...", titlePlaceholder: "标题...", contentPlaceholder: "内容...",
        general: "常规", appearance: "外观", physics: "物理", layout: "布局", shortcutsTab: "快捷键",
        collisionPadding: "碰撞间距", minimalGapRatio: "最小间隙", segmentHighlights: "显示高亮",
        center: "居中", side: "侧边", box: "方框",
        repel: "斥力", attract: "引力", linkGap: "连线间距",
        noNodes: "未找到节点",
        text: "文本", link: "链接",
        viewModeReadOnly: "视图模式 (只读)", editMode: "编辑模式",
        deleteConfirmation: "确定要删除",
        confirm: "确认", ok: "确定", error: "错误", invalidFile: "无效的 MathMap 文件",
        importFailed: "导入失败", sceneLoaded: "场景已加载", libraryLoaded: "库已加载",
        file: "文件", undo: "撤销", redo: "重做", autoSave: "自动保存",
        newScene: "新建场景", openScene: "打开场景", saveScene: "保存场景", saveAsScene: "另存为场景",
        modified: "已修改", unsavedChanges: "未保存的更改", close: "关闭", saving: "保存中..."
    },
    fr: {
        explorer: "Explorateur", settings: "Paramètres", newNode: "Nouveau Nœud", sceneOutline: "PLAN DE SCÈNE",
        theme: "Thème", gravity: "Gravité", centering: "Centrage", distance: "Distance", showTooltips: "Afficher les info-bulles",
        showMinimap: "Afficher la mini-carte", PHYandLAY: "Physique & Disposition", searchText: "Recherche...", livePreview: "Aperçu en direct",
        language: "Langue", export: "Exporter", import: "Importer", editNode: "Modifier le contenu du nœud",
        id: "ID", idHelp: "Lettres, chiffres et underscores uniquement.",
        title: "Titre", type: "Type", color: "Couleur", template: "Modèle LaTeX",
        segments: "Segments interactifs", addSegment: "Ajouter un segment", note: "Note (Markdown)",
        cancel: "Annuler", save: "Enregistrer les modifications", delete: "Supprimer le nœud", tooltipSettings: "Paramètres des info-bulles",
        customizeConnection: "Personnaliser la connexion", edgeLabel: "Étiquette de connexion", lineStyle: "Style de ligne",
        stroke: "Trait", endpoint: "Extrémité", showArrowInMiddle: "Afficher la flèche au milieu",
        showEdgeLabels: "Afficher les étiquettes de connexion", edgeLabelMode: "Position de l'étiquette", edgeLabelBg: "Fond de l'étiquette",
        minimapLabel: "Étiquette de la mini-carte", id: "ID", title: "Titre", none: "Aucun",
        pixelMode: "Mode Pixel", pixelFont: "Police Pixel", pixelMath: "Maths Pixel", minimalMode: "Mode Minimal",
        expandAll: "Tout développer", autoArrange: "Arrangement automatique",
        focus: "Focus", pin: "Épingler", unpin: "Désépingler", hide: "Masquer", show: "Afficher", edit: "Éditer",
        library: "Bibliothèque", searchLibrary: "Rechercher...", importLibrary: "Importer", exportLibrary: "Exporter",
        folder: "Dossier", tags: "Tags", moveToRoot: "Déplacer vers la racine", editTemplate: "Éditer le modèle", rename: "Renommer", duplicate: "Dupliquer",
        newFolder: "Nouveau Dossier", treeView: "Vue Arborescente", listView: "Vue Liste", gridView: "Vue Grille", viewSwitcher: "Changeur de Vue",
        collapseAll: "Tout réduire", refresh: "Actualiser",
        align: "Aligner", alignLeft: "Gauche", alignRight: "Droite", alignTop: "Haut", alignBottom: "Bas", alignCenterH: "Centre H", alignCenterV: "Centre V",
        shortcuts: { new: "Nouveau Nœud", refresh: "Actualiser", copy: "Copier", paste: "Coller", cut: "Couper", delete: "Supprimer", toggleViewMode: "Mode Vue" },
        types: { default: "Défaut", axiom: "Axiome", constant: "Constante", parameter: "Paramètre", note: "Note" },
        noSegments: "Aucun segment défini.", connectionStyle: "Style de Connexion", targetId: "ID Cible", linkColor: "Couleur du Lien",
        tooltipPlaceholder: "Contenu de l'info-bulle...", titlePlaceholder: "Titre...", contentPlaceholder: "Contenu...",
        general: "Général", appearance: "Apparence", physics: "Physique", layout: "Disposition", shortcutsTab: "Raccourcis",
        collisionPadding: "Marge de Collision", minimalGapRatio: "Écart Minimal", segmentHighlights: "Afficher les Surbrillances",
        center: "Centre", side: "Côté", box: "Boîte",
        repel: "Repousser", attract: "Attirer", linkGap: "Écart de Lien",
        noNodes: "Aucun nœud trouvé",
        text: "Texte", link: "Lien",
        viewModeReadOnly: "Mode Vue (Lecture seule)", editMode: "Mode Édition",
        deleteConfirmation: "Êtes-vous sûr de vouloir supprimer",
        confirm: "Confirmer", ok: "OK", error: "Erreur", invalidFile: "Fichier MathMap invalide",
        importFailed: "Échec de l'importation", sceneLoaded: "Scène chargée", libraryLoaded: "Bibliothèque chargée",
        file: "Fichier", undo: "Annuler", redo: "Rétablir", autoSave: "Sauvegarde auto",
        newScene: "Nouvelle Scène", openScene: "Ouvrir Scène", saveScene: "Enregistrer Scène", saveAsScene: "Enregistrer sous...",
        modified: "Modifié", unsavedChanges: "Modifications non enregistrées", close: "Fermer", saving: "Enregistrement..."
    },
    jp: {
        explorer: "エクスプローラー", settings: "設定", newNode: "新しいノード", sceneOutline: "シーン概要",
        theme: "テーマ", gravity: "重力", centering: "中心化", distance: "距離", showTooltips: "ツールチップを表示",
        showMinimap: "ミニマップを表示", PHYandLAY: "物理とレイアウト", searchText: "検索...", livePreview: "ライブプレビュー",
        language: "言語", export: "エクスポート", import: "インポート", editNode: "ノード内容を編集",
        id: "ID", idHelp: "英数字とアンダースコアのみ。",
        title: "タイトル", type: "タイプ", color: "色", template: "LaTeX テンプレート",
        segments: "インタラクティブセグメント", addSegment: "セグメントを追加", note: "ノート (Markdown)",
        cancel: "キャンセル", save: "変更を保存", delete: "ノードを削除", tooltipSettings: "ツールチップ設定",
        customizeConnection: "接続をカスタマイズ", edgeLabel: "エッジラベル", lineStyle: "線のスタイル",
        stroke: "ストローク", endpoint: "エンドポイント", showArrowInMiddle: "中央に矢印を表示",
        showEdgeLabels: "エッジラベルを表示", edgeLabelMode: "ラベル位置", edgeLabelBg: "ラベル背景",
        minimapLabel: "ミニマップラベル", id: "ID", title: "タイトル", none: "なし",
        pixelMode: "ピクセルモード", pixelFont: "ピクセルフォント", pixelMath: "ピクセル数式", minimalMode: "ミニマルモード",
        expandAll: "すべて展開", autoArrange: "自動配置",
        focus: "フォーカス", pin: "ピン留め", unpin: "ピン留め解除", hide: "隠す", show: "表示", edit: "編集",
        library: "ライブラリ", searchLibrary: "検索...", importLibrary: "インポート", exportLibrary: "エクスポート",
        folder: "フォルダ", tags: "タグ", moveToRoot: "ルートに移動", editTemplate: "テンプレートを編集", rename: "名前を変更", duplicate: "複製",
        newFolder: "新しいフォルダ", treeView: "ツリー表示", listView: "リスト表示", gridView: "グリッド表示", viewSwitcher: "表示切替",
        collapseAll: "すべて折りたたむ", refresh: "更新",
        align: "整列", alignLeft: "左揃え", alignRight: "右揃え", alignTop: "上揃え", alignBottom: "下揃え", alignCenterH: "水平中央", alignCenterV: "垂直中央",
        shortcuts: { new: "新しいノード", refresh: "更新", copy: "コピー", paste: "貼り付け", cut: "切り取り", delete: "削除", toggleViewMode: "表示モード切替" },
        types: { default: "デフォルト", axiom: "公理", constant: "定数", parameter: "パラメータ", note: "ノート" },
        noSegments: "セグメントが定義されていません。", connectionStyle: "接続スタイル", targetId: "ターゲットID", linkColor: "リンク色",
        tooltipPlaceholder: "ツールチップの内容...", titlePlaceholder: "タイトル...", contentPlaceholder: "内容...",
        general: "一般", appearance: "外観", physics: "物理", layout: "レイアウト", shortcutsTab: "ショートカット",
        collisionPadding: "衝突パディング", minimalGapRatio: "最小ギャップ", segmentHighlights: "ハイライトを表示",
        center: "中央", side: "側面", box: "ボックス",
        repel: "反発", attract: "引力", linkGap: "リンク間隔",
        noNodes: "ノードが見つかりません",
        text: "テキスト", link: "リンク",
        viewModeReadOnly: "表示モード (読み取り専用)", editMode: "編集モード",
        deleteConfirmation: "本当に削除しますか",
        confirm: "確認", ok: "OK", error: "エラー", invalidFile: "無効な MathMap ファイル",
        importFailed: "インポートに失敗しました", sceneLoaded: "シーンが読み込まれました", libraryLoaded: "ライブラリが読み込まれました",
        file: "ファイル", undo: "元に戻す", redo: "やり直し", autoSave: "自動保存",
        newScene: "新規シーン", openScene: "シーンを開く", saveScene: "シーンを保存", saveAsScene: "名前を付けて保存",
        modified: "変更あり", unsavedChanges: "未保存の変更", close: "閉じる", saving: "保存中..."
    },
};

export const FALLBACK_LIBRARY = { "root": { title: "Start Here", type: "default", template: "\\text{Welcome}", note: "Click 'New Node' to begin.", segments: {} } };
export const FALLBACK_NODES = [ { id: "node-root", contentId: "root", x: window.innerWidth / 2, y: window.innerHeight / 2, color: COLORS[0] } ];
